# .prettierrc or .prettierrc.yaml
trailingComma: "es5"
tabWidth: 2
semi: true
singleQuote: true
overrides:
  - files: "*.css"
    options:
      singleQuote: true
  - files: "*.js"
    options:
      trailingComma: "es5"
  - files: "*.jsx"
    options:
      singleQuote: true
      trailingComma: "es5"
  - files: "*.html"
    options:
      singleQuote: true

